default_language_version:
  python: python3.9
repos:
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-json
    exclude: ^(.devcontainer|.vscode)/.*\.json$
  - id: check-xml
  - id: check-yaml
  - id: check-toml
  - id: mixed-line-ending
    args: ['--fix=lf']
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    additional_dependencies: ["toml"]
